services:
  ollama:
    image: ${OLLAMA_IMAGE}
    container_name: ${OLLAMA_CONTAINTER_NAME}
    pull_policy: ${OLLAMA_PULL_POLICY}
    ports:
      - ${OLLAMA_HOST_PORT}:11434
    volumes:
      - ${OLLAMA_VOLUMES}
    restart: ${OLLAMA_RESTART}
