services:
  model-manager:
    image: ${OLLAMA_IMAGE}
    container_name: model-manager
    volumes:
      - ollama:/root/.ollama
      - ./scripts:/tmp/scripts:ro
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    depends_on:
      - ollama
    entrypoint: [ "/bin/bash" ]
    command: [ "/tmp/scripts/model-manager.sh" ]
    restart: "no"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: missing
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama:
  open-webui:
