services:
  model-manager:
    image: ${OLLAMA_IMAGE}
    container_name: model-manager
    volumes:
      - ollama:/root/.ollama
      - ./scripts:/tmp/scripts:ro
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    depends_on:
      - ollama
    entrypoint: [ "/bin/bash" ]
    command: [ "/tmp/scripts/model-manager.sh" ]
    restart: "no"

  ollama-metrics:
    image: ${OLLAMA_METRICS_IMAGE}
    container_name: ${OLLAMA_METRICS_CONTAINTER_NAME}
    pull_policy: missing
    ports:
      - "${OLLAMA_METRICS_HOST_PORT}:8080"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    depends_on:
      - ollama
    restart: unless-stopped

  open-webui:
    image: ${OPEN_WEBUI_IMAGE}
    container_name: open-webui
    pull_policy: missing
    ports:
      - "${OPEN_WEBUI_HOST_PORT}:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - ENABLE_PERSISTENT_CONFIG=False # https://docs.openwebui.com/reference/env-configuration/#important-note-on-persistentconfig-environment-variables
      - OLLAMA_BASE_URL="${OLLAMA_METRICS_HOST}"
    depends_on:
      - ollama-metrics

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    pull_policy: missing
    ports:
      - "${PROMETHEUS_HOST_PORT}:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
      - prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: ${GF_IMAGE}
    container_name: grafana
    pull_policy: missing
    ports:
      - "${GF_HOST_PORT}:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  ollama:
  open-webui:
  prometheus:
  grafana:
