services:
  model-manager:
    image: ${OLLAMA_IMAGE_AMD}
    container_name: model-manager
    volumes:
      - ollama:/root/.ollama
      - ./scripts:/scripts:ro
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    depends_on:
      - ollama
    entrypoint: [ "/bin/bash" ] # override the ollama entrypoint
    command: [ "/scripts/manage-models.sh" ]
    restart: no # run once and exit

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: missing
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama:
  open-webui:
